### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by ltsLumina** [ltsLumina/FG-GP-Team1#85]
- [x] Grab working as intended.

- [x] Grab animation should take the grabbed object, move it to the FakeFuel position, turn off the Grabbed Object, turn on the FakeFuel Model, then the animation will work, release should happen when the xxx function is called on the PlayerAnimation at the right time in the animation and do the reverse (set the grabbedobjects position, turn off the FakeFuel, turn on the GrabbedObject, and then give it that little initial velocity. Function that gets called when the item is released is PlayerAnimation.ObjectReleased(). This only applies to fuel, battery can stay as is

- [x] FakeFuel has a tag of FakeFuel or you can find it in the player model

- [x] Face Animations triggered from script by setting animation variables in PlayerAnimations animation controller. Triggers are in animation, logic SHOULD be ok, but I haven’t been able to test it.

- [x] Make sure the player is facing the ship during the repairing animation (look at ship transform?) I turned off movement rotation in animation while repairing so it should work in code.

- [x] Grabbing is still really sticky, sometimes it’s hard to let go sometimes it should just be a tap to grab and a tap to release
- [x] Propellor stops during the stun and never starts again (MotorSpeed animation float maybe being set to 0 and not raised back up to 1) (Skip if takes longer than 10 mins to fix)

- [ ] Fix any build breaking or game crashing bugs.

- [ ] audio branch

- [ ] build

**Comment by ltsLumina** [comment]
literally cant fix the tap to grab, tap to release. I don't understand why. it just doesn't work no matter what I try
